steps:
  # Build and deploy app1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy openapi-design to Cloud Run'
    dir: 'openapi-design'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'openapi-design'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY