steps:
  # Step 1: Build the specific Maven module
  - name: 'maven:3.9.2-eclipse-temurin-17'
    id: 'Build Maven Submodule'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'
      - '-pl'
      - 'json-servlet-example'
      - '-am'

  # Step 2: Automatically build and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'json-servlet-example'
      - '--source'
      - 'json-servlet-example'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'