steps:
  # Step 1: Build the specific Maven module
  - name: 'maven:3.9.2-eclipse-temurin-17'
    id: 'Build Maven Submodule'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'
      - '-pl'
      - 'json-servlet-example'
      - '-am'
  - name: 'ubuntu'
    id: 'Prepare Deployment Directory'
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
        mkdir -p /workspace/deployment
        cp -r json-servlet-example/* /workspace/deployment/
        cp -r json-servlet-example/target/*.jar /workspace/deployment/

  # Step 2: Automatically build and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    dir: '/workspace/deployment'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'json-servlet-example'
      - '--source'
      - '.'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY